model_opts:
  batch_norm : True
  inchannels: 6
  classes: 1
  lr: 0.0001
  weight_decay : 0

training_opts: 
  run_name: "test1"
  num_epochs: 10
  batch_size: 32

loss_opts:
  type: "CE_DiceLoss"
  smooth: 1
  weights_ce: 0.5
  weights_dice: 0.5

metrics_opts:
  IoU:
    threshold: 0.4
  pixel_acc:
    threshold: 0.4
  precision:
    threshold: 0.4
  recall:
    threshold: 0.4
  dice:
    threshold: 0.4

paths: 
  training:
    config_file: "/datadrive/glaciers/conf/train.yaml"
    #dataset_path: "../../scratch/izar/suply/dataset/data/output"
    dataset_path: "./data/output"
    save_path: "results"
  inference:
    config_file: "/datadrive/glaciers/conf/train.yaml"
    dataset_path: "path/to/data"
    test_csv: "path/to/csv"
    train_img_dir: "path/to/images" 
